version: '3.8'

networks:
  cybersentinel-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  # Nginx Reverse Proxy
  nginx:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-cybersentinel-ai}/nginx:${IMAGE_TAG:-latest}
    container_name: cybersentinel-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    volumes:
      - nginx_logs:/var/log/nginx
      - letsencrypt_certs:/etc/letsencrypt:ro
    networks:
      - cybersentinel-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Next.js Frontend
  frontend:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-cybersentinel-ai}/frontend:${IMAGE_TAG:-latest}
    container_name: cybersentinel-frontend
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://${DOMAIN:-cybersentinel.ai}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=https://${DOMAIN:-cybersentinel.ai}
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - frontend_cache:/app/.next/cache
    networks:
      - cybersentinel-network
    restart: unless-stopped
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # FastAPI Backend
  backend:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-cybersentinel-ai}/backend:${IMAGE_TAG:-latest}
    container_name: cybersentinel-backend
    expose:
      - "8000"
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@database:5432/cybersentinel
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENVIRONMENT=production
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - backend_data:/app/data
      - backend_logs:/app/logs
    networks:
      - cybersentinel-network
    restart: unless-stopped
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # PostgreSQL Database
  database:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-cybersentinel-ai}/database:${IMAGE_TAG:-latest}
    container_name: cybersentinel-database
    environment:
      - POSTGRES_DB=cybersentinel
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backups:/backups
    networks:
      - cybersentinel-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c max_connections=200
      -c shared_buffers=512MB
      -c effective_cache_size=2GB
      -c maintenance_work_mem=128MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: cybersentinel-redis
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - cybersentinel-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Backup Service
  backup:
    image: postgres:15-alpine
    container_name: cybersentinel-backup
    environment:
      - POSTGRES_DB=cybersentinel
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_backups:/backups
      - ./scripts/backup.sh:/backup.sh:ro
    networks:
      - cybersentinel-network
    restart: "no"
    command: >
      sh -c "
        while true; do
          sleep 86400
          /backup.sh
        done
      "
    depends_on:
      - database

volumes:
  postgres_data:
    driver: local
  postgres_backups:
    driver: local
  redis_data:
    driver: local
  nginx_logs:
    driver: local
  backend_data:
    driver: local
  backend_logs:
    driver: local
  frontend_cache:
    driver: local
  letsencrypt_certs:
    driver: local